name: Update SLIV Data

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run PHP script
      run: |
        php -r '
        $url = "https://raw.githubusercontent.com/Sarcastic-GOD/SLIV-LIVE/main/data.json";
        $content = file_get_contents($url);

        if ($content === false) {
            file_put_contents("sliv.json", json_encode(["error" => "Failed to fetch content from GitHub"]));
            exit(1);
        }

        $matchesData = json_decode($content, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            file_put_contents("sliv.json", json_encode(["error" => "Failed to parse JSON data"]));
            exit(1);
        }

        $output = [
            "name" => "Sonyliv Live Matches Data in Json",
            "telegram" => "https://t.me/CricDynasty",
            "matches" => $matchesData
        ];

        file_put_contents("sliv.json", json_encode($output, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        '

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add sliv.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update sliv.json with latest data"
        git push
